### PR TITLE
Add assertive-style assertions

### PR DESCRIPTION
**Pull request by johan**
This PR:

* [x] converts bond's test suite to friendlier `assertive` equivalents (or stronger tests) (*)
* [x] adds assertive-style assertion verbs with as clear failure output for:
  * [x] `calledOnceWithArgs(bondFunctionNameString, bondFn, args...)`
  * [x] `calledNTimesWithArgs(n, bondFunctionNameString, bondFn, argLists...)`
  * [ ] docs
  * [ ] tests

I'd like to have the implementation of these in the `bond` repo rather than something like assertive, as it depends on (and hides) the private implementation details of how bond stores call details from the assertion user, rather than littering test suites all over with those bits.

if you think it's a good idea (after likely adjustments), I'll add tests, update docs and whatever other bits might be omitted in the current spike state.

(*) first commit, for easy separation if you'd like it in its own PR / cherry-pick, for beautiful history

### CODE REVIEW

**Comment by johan** [comment]
@EndangeredMassa What's your take on the direction of this? I'd like to get some stronger, less syntax burdened bond assertions into a few test suites, and wonder if it's okay to add `assertive` among the direct dependencies like this. Still fairly small impact, size-wise.

**Comment by EndangeredMassa** [comment]
I like these assertions, but I'm not a big fan of adding a dependency. Going from 0 to 1 is a significant change.

In node, this isn't a big deal. In the browser, this means the user has to pull in assertive before bond. If they want to use a different assertion library for their non-bond assertions, then they are loading two different libraries. This could lead to some devs using one and some the other. I feel like we wouldn't be setting devs up for success.

**Comment by johan** [comment]
So duplicate the bits I want in these tests from assertive, rather than reusing assertive's version? Or can you think of some nicer middle ground?

**Comment by EndangeredMassa** [comment]
Either that or provide a separate build that browsers could use that bundles the dep into a single file.

**Comment by EndangeredMassa** [comment]
@johan are you still interested in adding this?

**Comment by johan** [comment]
Sorry, I lost track of this PR. I'll close this and maintain it elsewhere instead, keeping assertive out of here, while also separating bond bits from the app I'm using it in.

**Comment by EndangeredMassa** [comment]
I gave up on this fight. I'm fine with publishing `bond` as commonjs only, now. If you want to make a new PR that depends on `assertive`, feel free!

**Pull request closed without merging**
